name: Build hogehoge
on:
  push:
    branches:
      - test
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      targetwar: ${{ steps.builder.outputs.targetwar }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "21"
      - name: building
        id: builder
        run: |
          cd ./spring/demo
          ./gradlew bootWar
          TARGET_WAR=$(./build/libs/demo-0.0.1-SNAPSHOT.war)
          echo $TARGET_WAR
          echo "targetwar=${TARGET_WAR}" >> "$GITHUB_OUTPUT"
      - uses: actions/upload-artifact@v4
        with:
          name: targetwar
          path: ${{ steps.builder.outputs.targetwar }}
